{
 "title": "CI Details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "label": "CI ClassName",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   { "name": "metric", "label": "KPI" },
   {
    "name": "allMetrics",
    "label": "All Metrics",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CI Attributes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "CI Summary", "label": "CI Summary", "value": "CI_Summary" },
       "selectedSourceList": [
        {
         "__isNew__": true,
         "label": "$ci",
         "value": "$ci"
        }
       ],
       "service": "$service",
       "source": "$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "KPI Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
     "repeat": "metric",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metricName": "$metric",
       "metricType": "*",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
       "selectedMetricNameList": [
        {
         "__isNew__": true,
         "label": "$metric",
         "value": "$metric"
        }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": { "label": "Stock Trader Online", "value": "Stock Trader Online" },
       "selectedSourceList": [
        {
         "__isNew__": true,
         "label": "$ci",
         "value": "$ci"
        }
       ],
       "service": "Stock Trader Online",
       "source": "$ci"
      }
     ]
    }
   ]
  },
  { "title": "ITOM Alerts ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "source": "$ci"
    }
   ]
  },
  { "title": "All Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$allMetrics",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "repeat": "allMetrics",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricAnomaly": "false",
     "metricName": "$allMetrics",
     "metricType": "*",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
     "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
     "selectedMetricNameList": [
      {
       "__isNew__": true,
       "label": "$allMetrics",
       "value": "$allMetrics"
      }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$service",
      "value": "$service"
     },
     "selectedSourceList": [
      {
       "__isNew__": true,
       "label": "$ci",
       "value": "$ci"
      }
     ],
     "service": "Stock Trader Online",
     "source": "$ci"
    }
   ]
  },
  {
   "title": "Metrics Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metricName": "*",
     "metricType": "*",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
     "selectedMetricNameList": [
      { "label": "*", "value": "*" }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": { "label": "Stock Trader Online", "value": "Stock Trader Online" },
     "selectedSourceList": [
      {
       "__isNew__": true,
       "label": "$ci",
       "value": "$ci"
      }
     ],
     "service": "Stock Trader Online",
     "source": "$ci"
    }
   ]
  },
  {
   "title": "Recent Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recent Changes",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": { "description": "Get Alerts at the CI level", "label": "CI", "value": "CI" },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$services",
       "source": "$ci"
      }
     ]
    }
   ]
  }
 ]
}